server:
  port: 8080
  servlet:
    contextPath: /busroute

spring:
  application:
    name: busroute-generator
  profiles:
    active: local


gbis:
  base-url: http://openapi.gbis.go.kr/ws/rest
  service-key: HD%2BtUBYYJplyN8UPJPPp28aQYj03qS%2F4mEQ6X5cyc2C6426SyBnfvEd3bfiyBtwPHoqF8IyQJfdO%2BTErrHCdTQ%3D%3D


---
spring:
  profiles: local
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/local?currentSchema=busroute&charSet=utf-8&prepareThreshold=1
    username: postgres
    password: park3852
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
    sql-script-encoding: UTF-8