server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  application:
    name: busroute-generator
  profiles:
    active: local


hosts:
  gbis:
    base-url: http://openapi.gbis.go.kr/ws/rest
    service-key: HD%2BtUBYYJplyN8UPJPPp28aQYj03qS%2F4mEQ6X5cyc2C6426SyBnfvEd3bfiyBtwPHoqF8IyQJfdO%2BTErrHCdTQ%3D%3D
  open-route:
    base-url: https://api.openrouteservice.org
    api-key: 5b3ce3597851110001cf6248d949e059851c45e39536b69bc5033251


---
spring:
  profiles: local
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/local?currentSchema=busroute&charSet=utf-8&prepareThreshold=1
    username: postgres
    password: park3852
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
    sql-script-encoding: UTF-8